### ISSUE TITLE
Feature: Run DevPod on Spot Instances

### ISSUE THREAD

**Issue by theurichde** [loft-sh/devpod-provider-aws#12]
Hi folks! First, thank you for this nice provider 🚀

I was wondering why one should not run a devpod machine on an AWS spot instance. This would save some extra money 😅

I already [started working on that](https://github.com/theurichde/devpod-provider-aws/commit/bd2c88239fb74249a711ca7147eebb7f0233836b), the spot instance is already created and working. Proper stopping and spot request handling needs to be implemented.

I am creating this issue to gather overall feedback on that idea. Is that something that you would like to see in the provider? If so, I would provide the necessary implementation.

Cheers!

**Comment by FabianKramm** [comment]
Hey @theurichde, thanks for creating this issue! Yeah thats a cool idea, we would be happy to review a PR for that!

**Comment by alexandradragodan** [comment]
Hey, Tim! 
Thanks for the suggestion. 

Are you still working on this issue(or planning to)? 
Please let us know if there's anything we can support you with! 

Thanks.

**Comment by theurichde** [comment]
Hey there 👋🏻 

Yeah, I worked on that topic already, and I will continue when my time allows it 😅 

I did some quite opinionated changes which we can discuss
* The main change I did was, to create a devpod specific VPC on demand if a boolean for "Create DevPod VPC" was set.

You can compare the changes [here](https://github.com/loft-sh/devpod-provider-aws/compare/main...theurichde:devpod-provider-aws:feat/spot_instances) if you like

**Comment by seanpoulter** [comment]
I'm interested too. How can I help?

**Comment by pan93412** [comment]
Hello! I have implemented the Spot instance support. It works well in my short-term test; however, as I'm unsure if AWS exhibits any different behaviors for Spot instances, I hope someone can help me test if it is functioning correctly.

To use this, you can configure a custom provider with the URL: `https://github.com/pan93412/devpod-provider-aws/releases/download/0.3.0/provider.yaml`

![CleanShot 2024-06-07 at 14 43 17@2x](https://github.com/loft-sh/devpod-provider-aws/assets/28441561/c0b1a729-02ad-40a1-b668-3078a0d7c34b)

Remember to enable the "Aws Use Spot Instance" option to ensure you are starting a Spot instance (it is not enabled by default):

![CleanShot 2024-06-07 at 14 44 02@2x](https://github.com/loft-sh/devpod-provider-aws/assets/28441561/05ddafa6-9b12-48e2-8962-df17a5d63342)

**Comment by algoORgoal** [comment]
@pan93412
Thanks for the feature :))
I'd like to use your custom provider for now, since official devpod doesn't offer spot VM option yet. Are you using that one in your daily dev environment? Is it working okay?

**Comment by pan93412** [comment]
> @pan93412
> 
> Thanks for the feature :))
> 
> I'd like to use your custom provider for now, since official devpod doesn't offer spot VM option yet. Are you using that one in your daily dev environment? Is it working okay?

Hello 👋

I was used it for my daily development environment. It was great with only a few bugs. However, I bought my new development device later, so I do not use DevPod anymore 🥺

**Comment by algoORgoal** [comment]
@pan93412 Thanks for your response!
I attempted to run aws with your setup. However, it seems like 2 instances are created when I chose m7g.xlarge as instance type. Did you go through the same thing? If so, can I just terminate the other instance(c5.xlarge)?
![image](https://github.com/loft-sh/devpod-provider-aws/assets/19303532/cab887a5-5854-49db-b347-b8500b8557ff)

**Comment by pan93412** [comment]
> @pan93412 Thanks for your response! I attempted to run aws with your setup. However, it seems like 2 instances are created when I chose m7g.xlarge as instance type. Did you go through the same thing? If so, can I just terminate the other instance(c5.xlarge)? ![image](https://private-user-images.githubusercontent.com/19303532/345334444-cab887a5-5854-49db-b347-b8500b8557ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTQyMzksIm5iZiI6MTcxOTk5MzkzOSwicGF0aCI6Ii8xOTMwMzUzMi8zNDUzMzQ0NDQtY2FiODg3YTUtNTg1NC00OWRiLWIzNDctYjg1MDBiODU1N2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA4MDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NGI5YTYwMmY1Yzg2ZDE1ZDcxNWQ3MzY5YzE4MTg2OGEwYzMzODhiZDc2Yjc4M2Q4ZDVhZDk2NjkwNWMzZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S93pWKXcKsH02IY4vtEkTt86y4o67k6C19_J175kRX8)

Not sure why `c5.xlarge` starts as no code declared it.
