### ISSUE TITLE
Document necessary IAM permissions

### ISSUE THREAD

**Issue by artis3n** [loft-sh/devpod-provider-aws#15]
I'm looking to setup an IAM role to leverage [short-term credentials](https://github.com/loft-sh/devpod-provider-aws/issues/2) to access AWS from [devpod.sh](http://devpod.sh). What are the minimal IAM permissions necessary for devpod to function?

I imagine the managed `AmazonEC2FullAccess` policy would suffice, but are there additional permissions needed? Are *all* the policies under `AmazonEC2FullAccess` needed, or would subset be sufficient?

It would be very useful to include a sample IAM policy / table of IAM permissions on the README documenting what permission is needed for what use case.

**Comment by 89luca89** [comment]
Hi @artis3n that's true, this needs to be documented

The IAM role should provide permissions to:

- create a subnet if you don't plan to provide an existing one
- create an instance profile if you don't plan to provide an existing one
    - the instance profile should be able to stop/destroy the instance itself
- create a security group if you don't plan to provide an existing one
- create, stop and destroy an instance

It should be all, but let me know if this is not enough, I plan to add a doc page for it asap :+1:
