### ISSUE TITLE
Feature Request: Allow using short term credentials

### ISSUE THREAD

**Issue by knguyen0125** [loft-sh/devpod-provider-aws#2]
I'm evaluating this AWS plugin for our company, and it looks like we can only use long-term AWS credentials.

Our company moved to AWS SSO / Identity Center a while ago, and is currently using [AWS SSO CLI](https://github.com/synfinatic/aws-sso-cli) as credential process. It's not working, even with providing AWS credentials option as environment variable.

Further investigation seems to be due to the GetSessionToken call, which can only be called with long-term token.

Shouldn't the long-term token be enough without calling the API to get session token? The GetSessionToken api call only seem to be used for authenticating with MFA ([https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html)), which we don't provide anything in this case.

**Comment by joebowbeer** [comment]
Me too. I would like to provide AWS_PROFILE instead.

**Comment by 89luca89** [comment]
Thanks for the report! I'm working on this :smile:
