### ISSUE TITLE
Support AMIs that do not use `/dev/sda1` for the root device

### ISSUE THREAD

**Issue by dlacosteGFM** [loft-sh/devpod-provider-aws#25]
This one is pretty simple: I have to use Amazon Linux because our org already has that fully deployed everywhere else, but I still want to use DevPod!

Unfortunately, when I resize the disk with `AWS_DISK_SIZE` it adds a _second_ volume named `/dev/sda1` rather than applying the property to the image's root device `/dev/xda1`.

I made a PR to set the value to whatever is defined in the AMI, or to override on the command line: https://github.com/loft-sh/devpod-provider-aws/pull/24

**Comment by pascalbreuninger** [comment]
closed by #24
