### ISSUE TITLE
StatusCode 401: AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by SinBirb** [loft-sh/devpod-provider-aws#28]
Hi, I'm using AWS with [aws-vault](https://github.com/99designs/aws-vault) which devpod didn't work with at first. Last Friday I managed to set it up but am not sure exactly why it worked.
I tried to use AWS_PROFILE as well as AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and ran it inside the aws-vault shell when it finally worked.

However now, I cannot up the workspace anymore, this it the output:

```bash
❯ devpod up --debug gitlab.exmaple.com/project
08:20:10 info Workspace sst-cognito already exists
08:20:10 debug Acquire workspace lock...
08:20:10 debug Acquired workspace lock...
08:20:10 debug Acquire machine lock...
08:20:10 debug Acquired machine lock...
08:20:10 debug Run status provider command: ${AWS_PROVIDER} status
08:20:11 fatal get status: operation error EC2: DescribeImages, https response error StatusCode: 401, RequestID: fcbac940-0000-0000-0000-40177a0c0000, api error AuthFailure: AWS was not able to validate the provided access credentials
```

**Comment by pascalbreuninger** [comment]
Hey @SinBirb, thanks for reporting the issue. I'm not familiar with aws-vault at all. If you could narrow the problem further down to where the kubernetes provider fails, I could maybe help you. Alternatively a reproducible example setup, or steps to create one, would also help
