### ISSUE TITLE
AWS_TOKEN was not removed even after expiration

### ISSUE THREAD

**Issue by vegasje** [loft-sh/devpod-provider-aws#3]
This morning I attempted to pick up from where I had left off the night before using DevPod.
All commands I ran encountered the same error: `fatal get status: RequestExpired: Request has expired.`

After doing some digging, I found that the provider was attempting to use the `AWS_TOKEN` value stored in `~/.devpod/contexts/default/machines/[machine-name]/machine.json`, of which the `Expiration` value had already passed.

I removed the `AWS_TOKEN` entry from `machine.json` and was able to execute commands again.

I'm not sure what process is responsible for cleaning up this expired `AWS_TOKEN` (DevPod or the provider), but it would be a good idea for the provider to check the expiration on the token before attempting to use it.

**Comment by 89luca89** [comment]
Hi @vegasje 
Thanks for reporting! I'll check on this :+1:
