### ISSUE TITLE
AWS_INSTANCE_TAGS doesn't support special symbols like : or .

### ISSUE THREAD

**Issue by alexk2000** [loft-sh/devpod-provider-aws#32]
When special characters like : or . are used in EC2 instance tag values, the text after these symbols gets truncated.

`devpod provider set-options aws --option AWS_INSTANCE_TAGS="Name=CreatedBy,Value=AROAWIWEDDH5JQNEI3H3F:John.Doe"`

![изображение](https://github.com/loft-sh/devpod-provider-aws/assets/28801418/7be50acb-0d1c-4257-88ed-bcb119394182)

In my case tag CreatedBy contains aws:userid for SAML federated user which has format  role-id:caller-specified-role-name (see [details](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html#policy-vars-infotouse))

Devpod version: 0.5.6
AWS provider version: 0.0.12

**Comment by alexk2000** [comment]
Thanks a lot for such fast solution !

**Comment by 89luca89** [comment]
Thanks for reporting, the new release will be available in some minutes, containing the fix :+1:
