### ISSUE TITLE
DevPod attempting to use the incorrect machine name

### ISSUE THREAD

**Issue by vegasje** [loft-sh/devpod-provider-aws#8]
I have an existing AWS instance, created by DevPod, that I wanted to access via SSH.

I issued the command:

`devpod machine ssh`

DevPod is appending an extra `devpod-` to the machine name when trying to locate it:

```
? *Please select a machine from the list below* devpod-shared-aws
13:17:20 info instance devpod-devpod-shared-aws doesn't exist
13:17:24 info instance devpod-devpod-shared-aws doesn't exist
13:17:24 info Waiting for devpod agent to come up...
13:17:28 info instance devpod-devpod-shared-aws doesn't exist
13:17:32 info instance devpod-devpod-shared-aws doesn't exist
13:17:32 info Waiting for devpod agent to come up...
13:17:36 info instance devpod-devpod-shared-aws doesn't exist
13:17:40 info instance devpod-devpod-shared-aws doesn't exist
13:17:40 info Waiting for devpod agent to come up...
13:17:44 info instance devpod-devpod-shared-aws doesn't exist
13:17:48 info instance devpod-devpod-shared-aws doesn't exist
13:17:48 info Waiting for devpod agent to come up...
...
```

I am using `devpod` 0\.1.9 and `devpod-provider-aws` 0\.0.4.
This started happening after updating `devpod-provider-aws` from version 0.0.2.

**Comment by 89luca89** [comment]
Hi @vegasje 
this machine was created using v0.0.2 and now ssh-ing in it with v0.0.4 doesn't work?

**Comment by vegasje** [comment]
@89luca89 The machine was created using v0.0.4.

**Comment by 89luca89** [comment]
Understood, sadly I can't reproduce this
I'm just using it now like:

```sh
devpod up ./
devpod machine ssh 
# then I select the machine just created
```

I'm using default settings for the provider, maybe you can give me more infos about the setup?
Thanks a lot!

**Comment by vegasje** [comment]
@89luca89 I'm happy to provide additional information.

I have configured my provider with:
- aws region
- aws profile
- aws disk size (40gb)
- aws instance type (t3.large)
- aws vpc id
- aws security group id

I also have the provider set to reuse the same machine for all workspaces.
I have a custom Docker image that is used to create the workspace.
I frequently delete and rebuild the workspace, as the `--recreate` flag does not appear to work with `devpod up` when using the AWS provider (or at least I have never been able to get it to work).

**Comment by 89luca89** [comment]
Hi @vegasje 

I've tried various ways, but I cannot reproduce this issue sadly, also for me recreate works correctly
Can you try with the latest provider/devpod?
